import { Product, Category, Brand, Banner, SiteSettings, Coupon, Review } from '@/types/ecommerce';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-chaser-machine',
    name: 'লকার মেশিন ও কন্ট্রোলার',
    slug: 'chaser-machine',
    description: '৩২ খেলা, ১৬ খেলা মরিচ বাতি খেলানোর ডিজিটাল লকার মেশিন, ফ্লাশার ও নাম ডিসপ্লে বোর্ড কন্ট্রোলার।',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    icon: 'Cpu',
    is_featured: true,
    display_order: 1,
    product_count: 2,
  },
  {
    id: 'cat-morich-bati',
    name: 'মরিচ বাতি ও ডেকোরেশন লাইট',
    slug: 'morich-bati',
    description: '১০০/২০০ এলইডি ওয়াটারপ্রুফ মরিচ বাতি, পিক্সেল লাইট ও রঙিন ডেকোরেশন চেইন লাইট।',
    image_url: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=600&q=80',
    icon: 'Sparkles',
    is_featured: true,
    display_order: 2,
    product_count: 2,
  },
  {
    id: 'cat-tv-parts',
    name: 'টিভি রিপেয়ারিং পার্টস',
    slug: 'tv-parts',
    description: 'ইউনিভার্সাল এলইডি টিভি মাদারবোর্ড, ব্যাকলাইট টেস্টার, সিআরটি টিভি কিট ও রিমোট।',
    image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
    icon: 'Tv',
    is_featured: true,
    display_order: 3,
    product_count: 3,
  },
  {
    id: 'cat-tools',
    name: 'সার্ভিসিং ও সোল্ডারিং টুলস',
    slug: 'tools',
    description: 'ডিজিটাল মাল্টিমিটার, ৬০W অ্যাডজাস্টেবল তাতাল, রাং, রজন ও ডিসোল্ডারিং সাকশন পাম্প।',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    icon: 'Wrench',
    is_featured: true,
    display_order: 4,
    product_count: 4,
  },
  {
    id: 'cat-blender-parts',
    name: 'ব্লেন্ডার মোটর ও পার্টস',
    slug: 'blender-parts',
    description: '৭৫০W পিওর কপার ব্লেন্ডার মোটর, ইউনিভার্সাল রাবার কাপলার ও জার ব্লেড অ্যাসেম্বলি।',
    image_url: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=600&q=80',
    icon: 'Layers',
    is_featured: true,
    display_order: 5,
    product_count: 2,
  },
  {
    id: 'cat-audio-amp',
    name: 'অডিও অ্যামপ্লিফায়ার ও মডিউল',
    slug: 'audio-amp',
    description: '২.১ চ্যানেল ব্লুটুথ অ্যামপ্লিফায়ার বোর্ড, ১২V ব্লুটুথ MP3 মডিউল ও সাউন্ড সিস্টেম এক্সেসরিজ।',
    image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80',
    icon: 'Headphones',
    is_featured: true,
    display_order: 6,
    product_count: 2,
  },
  {
    id: 'cat-power-battery',
    name: 'পাওয়ার অ্যাডাপ্টার ও ব্যাটারি',
    slug: 'power-battery',
    description: '১২V ৫A এসএমপিএস পাওয়ার অ্যাডাপ্টার ও ৩এস লিথিয়াম ব্যাটারি বিএমএস প্রোটেকশন বোর্ড।',
    image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80',
    icon: 'Zap',
    is_featured: true,
    display_order: 7,
    product_count: 2,
  },
  {
    id: 'cat-cc-camera',
    name: 'সিসি ক্যামেরা ও অ্যাক্সেসরিজ',
    slug: 'cc-camera',
    description: 'এইচডি নাইট ভিশন সিসি ক্যামেরা, বিএনসি ও ডিসি পিন কানেক্টর প্যাক।',
    image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80',
    icon: 'Shield',
    is_featured: true,
    display_order: 8,
    product_count: 1,
  },
];

export const INITIAL_BRANDS: Brand[] = [
  { id: 'brand-servicing-world', name: 'Servicing World', slug: 'servicing-world', is_featured: true },
  { id: 'brand-chaser-pro', name: 'Chaser Pro', slug: 'chaser-pro', is_featured: true },
  { id: 'brand-universal', name: 'China Universal', slug: 'china-universal', is_featured: true },
  { id: 'brand-dt-tools', name: 'DT Tools', slug: 'dt-tools', is_featured: true },
  { id: 'brand-heavy-copper', name: 'Heavy Copper', slug: 'heavy-copper', is_featured: true },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    title: '৩২ খেলার ডিজিটাল লকার মেশিন (32 Channel Morich Bati Chaser Controller)',
    slug: '32-channel-digital-chaser-machine',
    sku: 'SW-CHASER-32CH',
    short_description: '৩২ চ্যানেল মাইক্রোকন্ট্রোলার পরিচালিত মরিচ বাতি খেলানোর ডিজিটাল লকার মেশিন ও ফ্লাশার।',
    description: 'সার্ভিসিং ওয়ার্ল্ডের নিজস্ব টেস্টিং ল্যাবে তৈরিকৃত ও পরীক্ষিত ৩২ খেলার হেভি ডিউটি ডিজিটাল লকার মেশিন। বিয়ে বাড়ি, পূজা-পার্বণ ও যে কোনো ডেকোরেশন লাইটিংয়ে মরিচ বাতির নান্দনিক রানিং, ওয়েভ ও ফ্লাশিং ইফেক্ট তৈরি করতে এটি অতুলনীয়। এতে প্রতিটি চ্যানেলে নির্ভরযোগ্য মসফেট/ট্রায়াক ড্রাইভ ও স্পিড কন্ট্রোল নোব রয়েছে।',
    price: 1850,
    discount_price: 1650,
    stock: 25,
    min_stock_warning: 3,
    category: 'chaser-machine',
    brand: 'Servicing World',
    main_image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: '৬ মাসের সার্ভিসিং ওয়ারেন্টি',
    shipping_info: 'সারাদেশে সুন্দরবন বা রেডএক্স কুরিয়ারে ২৪-৪৮ ঘণ্টার মধ্যে ক্যাশ অন ডেলিভারি।',
    return_info: 'ডেলিভারি পাওয়ার পর কাজ না করলে তাৎক্ষণিক বদলানোর গ্যারান্টি।',
    tags: ['chaser machine', 'locker machine', 'morich bati', '32 channel', 'lighting controller', 'servicing world'],
    features: [
      '৩২টি পৃথক চ্যানেল ড্রাইভার আউটপুট',
      '৩২ রকমের অটোমেটিক ডিজাইনিং ও রানিং লাইট খেলা',
      'ম্যানুয়াল স্পিড অ্যাডজাস্টমেন্ট ভলিউম কন্ট্রোলার',
      'হেভি ডিউটি কুলিং হিটসিঙ্ক প্রযুক্তি',
      '২২০V এসি ডাইরেক্ট ইনপুট সাপোর্ট',
    ],
    specifications: [
      { spec_group: 'Technical', key: 'চ্যানেল সংখ্যা', value: '৩২ চ্যানেল (32 Ways)' },
      { spec_group: 'Technical', key: 'ইনপুট ভোল্টেজ', value: 'AC 220V 50Hz' },
      { spec_group: 'Technical', key: 'সর্বোচ্চ লোড প্রতি চ্যানেল', value: '১০০ ওয়াট' },
      { spec_group: 'Physical', key: 'বডি মেটেরিয়াল', value: 'মেটাল / হেভি ডিউটি ফাইবার চেসিস' },
      { spec_group: 'Physical', key: 'উৎপাদন ও পরীক্ষা', value: 'সার্ভিসিং ওয়ার্ল্ড হার্ডওয়্যার ল্যাব' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.9,
    review_count: 38,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    title: '১৬ খেলার ডিজিটাল লকার ফ্লাশার মেশিন (16 Channel Chaser Machine)',
    slug: '16-channel-digital-chaser-machine',
    sku: 'SW-CHASER-16CH',
    short_description: '১৬ চ্যানেল ডিজিটাল মরিচ বাতি কন্ট্রোলার ও অটোমেটিক ফ্লাশার মেশিন।',
    description: 'ছোট ও মাঝারি ডেকোরেশন এবং দোকান বা গেট সাজানোর জন্য আদর্শ ১৬ খেলার ডিজিটাল লকার মেশিন। ১৬টি চ্যানেলে ভিন্ন ভিন্ন রানিং ও স্পার্কলিং খেলা নিয়ন্ত্রণের পাশাপাশি স্পিড কমানো বা বাড়ানোর পুর্ণ সুবিধা রয়েছে।',
    price: 1250,
    discount_price: 1100,
    stock: 30,
    min_stock_warning: 4,
    category: 'chaser-machine',
    brand: 'Servicing World',
    main_image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: '৬ মাসের সার্ভিসিং ওয়ারেন্টি',
    shipping_info: '২৪-৪৮ ঘণ্টার মধ্যে সারা বাংলাদেশে দ্রুত হোম ডেলিভারি।',
    return_info: '৭ দিনের রিপ্লেসমেন্ট সুবিধা।',
    tags: ['16 channel', 'chaser machine', 'locker machine', 'flasher', 'morich bati'],
    features: [
      '১৬টি পৃথক আউটপুট চ্যানেল',
      '১৬ প্রকার আকর্ষণীয় লাইট খেলা ইফেক্ট',
      'অটো ও ম্যানুয়াল স্পিড ভেরিয়েবল নব',
      'ওভারলোড নিরাপদ সার্কিট ডিজাইন',
    ],
    specifications: [
      { spec_group: 'Technical', key: 'চ্যানেল', value: '১৬ চ্যানেল' },
      { spec_group: 'Technical', key: 'ইনপুট ভোল্টেজ', value: 'AC 180V - 240V' },
      { spec_group: 'Technical', key: 'কন্ট্রোলার চিপ', value: 'প্রোগ্রামড মাইক্রোকন্ট্রোলার' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: false,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.8,
    review_count: 24,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    title: '১০০ এলইডি ওয়াটারপ্রুফ মরিচ বাতি মাল্টি কালার (100 LED Morich Bati 40 Feet)',
    slug: '100-led-waterproof-morich-bati-multicolor',
    sku: 'SW-LED-100RGB',
    short_description: '৪০ ফিট দীর্ঘ ১০০ পিস ব্রাইট মাল্টি-কালার এলইডি ওয়াটারপ্রুফ মরিচ বাতির মালা।',
    description: 'উৎসব, বিয়ে, পূজা ও যে কোনো উৎসবের সাজসজ্জার জন্য ১০০ পিস হাই-ব্রাইটনেস ওয়াটারপ্রুফ মাল্টি কালার মরিচ বাতি। এটি পিওর কপার তার দিয়ে তৈরি হওয়ায় সহজে ছিঁড়ে না এবং দীর্ঘদিন টেকসই থাকে। লকার বা চেজার মেশিনের সাথে ব্যবহারের জন্য সম্পূর্ণ উপযোগী।',
    price: 280,
    discount_price: 240,
    stock: 120,
    min_stock_warning: 15,
    category: 'morich-bati',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1543257580-7269da773bf5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514517521153-1be72277b32f?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: 'চেক অ্যান্ড রিসিভ ওয়ারেন্টি',
    shipping_info: 'সারাদেশে ক্যাশ অন ডেলিভারি। ৫ পিসের উপরে অর্ডারে বিশেষ ছাড়।',
    return_info: 'ডেলিভারির সময় চেক করে নেয়ার সুবিধা।',
    tags: ['morich bati', 'led light', 'rgb light', 'decoration', 'fairy lights'],
    features: [
      '১০০টি প্রিমিয়াম ব্রাইট এলইডি বাল্ব',
      'বৃষ্টি ও কুয়াশা প্রতিরোধী ওয়াটারপ্রুফ কোটিং',
      'লম্বা ৪০ ফিট শক্ত কপার ক্যাবল',
      'কম বিদ্যুৎ খরচ ও দীর্ঘস্থায়ী লাইফস্প্যান',
    ],
    specifications: [
      { spec_group: 'Light', key: 'বাল্ব সংখ্যা', value: '১০০ এলইডি' },
      { spec_group: 'Light', key: 'দৈর্ঘ্য', value: 'প্রায় ৪০ ফুট (12 Meter)' },
      { spec_group: 'Light', key: 'কালার', value: 'মাল্টি কালার (RGB)' },
      { spec_group: 'Power', key: 'ভোল্টেজ', value: '২২০V এসি' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.7,
    review_count: 52,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    title: '২০০ এলইডি হেভি কপার মরিচ বাতি - গোল্ডেন ওয়ার্ম হোয়াইট (200 LED 80 Feet)',
    slug: '200-led-heavy-copper-morich-bati-warm-white',
    sku: 'SW-LED-200WW',
    short_description: '৮০ ফিট দীর্ঘ ২০০ এলইডি হেভি পিওর কপার ওয়ার্ম হোয়াইট প্রিমিয়াম ডেকোরেশন লাইট।',
    description: 'প্রিমিয়াম কোয়ালিটির সোনালী ওয়ার্ম হোয়াইট কালারের ২০০ এলইডি মরিচ বাতি। বাড়ি, ভবন ও বাগানের দীর্ঘ পরিসরে আলো ছড়ানোর জন্য অত্যন্ত কার্যকর। তারের কোয়ালিটি মোটা ও ডাবল ইনসুলেটেড হওয়ায় রোদে ও পানিতে নষ্ট হয় না।',
    price: 550,
    discount_price: 480,
    stock: 80,
    min_stock_warning: 10,
    category: 'morich-bati',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1514517521153-1be72277b32f?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1514517521153-1be72277b32f?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: 'টেস্টিং ওয়ারেন্টি',
    shipping_info: '২৪ থেকে ৪৮ ঘণ্টার মধ্যে সারা দেশে হোম ডেলিভারি।',
    return_info: 'ত্রুটিপূর্ণ পেলে তাৎক্ষণিক পরিবর্তন।',
    tags: ['morich bati', 'warm white', '200 led', 'decoration light', 'copper wire'],
    features: [
      '২০০টি সুপার ব্রাইট সোনালী এলইডি',
      'লম্বা ৮০ ফুট কভারিং রেঞ্জ',
      '১০০% পিওর কপার হেভি ওয়্যার',
    ],
    specifications: [
      { spec_group: 'Light', key: 'বাল্ব সংখ্যা', value: '২০০ এলইডি' },
      { spec_group: 'Light', key: 'দৈর্ঘ্য', value: '৮০ ফুট (24 Meter)' },
      { spec_group: 'Light', key: 'কালার', value: 'গোল্ডেন ওয়ার্ম হোয়াইট' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: true,
    is_new_arrival: true,
    is_on_sale: true,
    average_rating: 4.8,
    review_count: 19,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    title: 'ইউনিভার্সাল এলইডি টিভি কম্বো মাদারবোর্ড কিট (T.V56 / T.V53 Universal Board + Remote)',
    slug: 'universal-led-tv-motherboard-kit-v56-v53',
    sku: 'SW-TV-UNIV-V56',
    short_description: '১৭ ইঞ্চি থেকে ৪৩ ইঞ্চি সকল ব্র্যান্ডের চায়না ও এলইডি টিভির জন্য ইউনিভার্সাল মাদারবোর্ড কিট।',
    description: 'যেকোনো ডেড এলইডি টিভি সচল করতে জনপ্রিয় T.V56 / T.V53 ইউনিভার্সাল কম্বো মাদারবোর্ড কিট। এতে রয়েছে HDMI, VGA, USB, AV ইনপুট ও অডিও আউটপুট। সাথে সম্পূর্ণ রিমোট কন্ট্রোল ও আইআর সেন্সর দেওয়া হয়। এটি সরাসরি ইউএসবি পেনড্রাইভ দিয়ে বিভিন্ন রেজোলিউশন সফটওয়্যার আপডেট করা যায়।',
    price: 1450,
    discount_price: 1300,
    stock: 40,
    min_stock_warning: 5,
    category: 'tv-parts',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: '৩ মাসের রিপ্লেসমেন্ট গ্যারান্টি (বার্ন বাদে)',
    shipping_info: 'সারাদেশে সুরক্ষিত অ্যান্টি-স্ট্যাটিক প্যাকেজিং সহ ক্যাশ অন ডেলিভারি।',
    return_info: 'ইনস্টল করার আগে টেকনিশিয়ান দ্বারা টেস্ট করে নিতে হবে।',
    tags: ['tv motherboard', 'led tv board', 'v56', 'v53', 'tv repairing', 'servicing world'],
    features: [
      '১৭ থেকে ৪৩ ইঞ্চি এলইডি প্যানেল সাপোর্ট',
      'ফুল এইচডি 1920x1080 পর্যন্ত রেজোলিউশন সাপোর্ট',
      'এইচডিএমআই, ভিজিএ, ইউএসবি ও এভি মাল্টিপল পোর্ট',
      'ইউএসবি দ্বারা সফটওয়্যার ও ফার্মওয়্যার আপগ্রেডেবল',
      'রিমোট কন্ট্রোল ও রিসিভার সেন্সর অন্তর্ভুক্ত',
    ],
    specifications: [
      { spec_group: 'General', key: 'বোর্ড মডেল', value: 'T.V56.031 / T.V53 Universal Board' },
      { spec_group: 'Panel Support', key: 'প্যানেল ইন্টারফেস', value: 'Single / Dual 6/8-bit LVDS' },
      { spec_group: 'Power', key: 'অপারেটিং ভোল্টেজ', value: '12V DC Input' },
      { spec_group: 'Audio', key: 'অডিও আউটপুট', value: '2x 5W Stereo Speaker' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.9,
    review_count: 47,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-006',
    title: 'ডিজিটাল এলইডি টিভি ব্যাকলাইট টেস্টার (0-300V Output Auto Voltage)',
    slug: 'digital-led-tv-backlight-tester-0-300v',
    sku: 'SW-TESTER-LED300',
    short_description: '০-৩০০ ভোল্ট অটো ভোল্টেজ ব্যাকলাইট ও সিঙ্গেল এলইডি টেস্টার ডিজিটাল ডিসপ্লে সহ।',
    description: 'টিভি মেকানিক ও টেকনিশিয়ানদের জন্য অপরিহার্য স্মার্ট এলইডি ব্যাকলাইট টেস্টার। টিভি প্যানেল না খুলেই যেকোনো এলইডি স্ট্রিপ বা ব্যাকলাইটের সিঙ্গেল বাল্ব নিখুঁতভাবে চেক করা যায়। এতে অটোমেটিক ভোল্টেজ ও কারেন্ট র্যাম্পিং ফিচার রয়েছে ফলে এলইডি বাল্ব কাটার কোনো ঝুঁকি থাকে না।',
    price: 1250,
    discount_price: 1100,
    stock: 22,
    min_stock_warning: 3,
    category: 'tv-parts',
    brand: 'DT Tools',
    main_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: '৬ মাসের সার্ভিসিং ওয়ারেন্টি',
    shipping_info: 'সারাদেশে দ্রুত ক্যাশ অন ডেলিভারি।',
    return_info: '৭ দিনের কার্যকারিতা গ্যারান্টি।',
    tags: ['backlight tester', 'led tester', 'tv repairing tools', '0-300v tester'],
    features: [
      '০ থেকে ৩০০ ভোল্ট অটো-অ্যাডজাস্টেবল আউটপুট',
      'রিয়েল-টাইম ডিজিটাল এলইডি ভোল্টেজ ডিসপ্লে',
      'সিঙ্গেল বাল্ব ও পুরো স্ট্রিপ উভয় পরীক্ষার সুবিধা',
      'শর্ট-সার্কিট ও অ্যান্টি-বার্ন ইন্টেলিজেন্ট সুরক্ষা',
    ],
    specifications: [
      { spec_group: 'Power', key: 'ইনপুট ভোল্টেজ', value: 'AC 85V - 265V' },
      { spec_group: 'Output', key: 'আউটপুট ভোল্টেজ', value: 'DC 0 - 300V Auto Adapt' },
      { spec_group: 'Display', key: 'ডিসপ্লে মোড', value: '৩ ডিজিট ডিজিটাল ভোল্টমিটার' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: false,
    is_new_arrival: true,
    is_on_sale: true,
    average_rating: 4.9,
    review_count: 29,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    title: 'সিআরটি টিভি কালার ইউনিভার্সাল মাদারবোর্ড কিট (14-21 Inch CRT TV Kit)',
    slug: 'crt-tv-universal-motherboard-kit-14-21-inch',
    sku: 'SW-CRT-KIT-21',
    short_description: '১৪ থেকে ২১ ইঞ্চি সকল কালার সিআরটি টিভির ফুল ইউনিভার্সাল মাদারবোর্ড কিট।',
    description: 'পুরাতন সিআরটি টিভি সম্পূর্ণ নতুনের মতো সচল করার জন্য ইউনিভার্সাল সিআরটি টিভি সার্কিট কিট। এতে টোশিবা/সানিয়া চিপসেট, সাউন্ড আইসি, ফ্লাইব্যাক ট্রান্সফরমার ও কানেক্টর ওয়্যার লাগানো রয়েছে। সম্পূর্ণ কিটের সাথে রিমোট ও ফ্রন্ট সেন্সর প্যানেল ফ্রি দেওয়া হয়।',
    price: 1150,
    discount_price: 980,
    stock: 18,
    min_stock_warning: 2,
    category: 'tv-parts',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: 'টেস্টিং ওয়ারেন্টি',
    shipping_info: 'সারা দেশে দ্রুত ক্যাশ অন ডেলিভারি।',
    return_info: 'কুরিয়ার থেকে খুলে চেক করার সুবিধা।',
    tags: ['crt tv', 'tv circuit', 'crt board', 'tv servicing'],
    features: [
      '১৪ থেকে ২১ ইঞ্চি সিআরটি টিউব সাপোর্ট',
      'স্ট্রং পাওয়ার সাপ্লাই ও ক্লিয়ার কালার ডেপথ',
      'কমপ্লিট রিমোট কন্ট্রোল ও ওয়্যারিং ক্যাবল অন্তর্ভুক্ত',
    ],
    specifications: [
      { spec_group: 'Compatibility', key: 'টিভি সাইজ', value: '14" - 21" Color CRT' },
      { spec_group: 'Power', key: 'ইনপুট ভোল্টেজ', value: 'AC 110V - 240V' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: false,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.6,
    review_count: 15,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    title: 'ডিটি-৯২০৫এ ডিজিটাল মাল্টিমিটার (DT-9205A Large Display Multimeter)',
    slug: 'dt9205a-digital-multimeter-large-display',
    sku: 'SW-METER-9205A',
    short_description: 'ইলেকট্রনিক্স টেকনিশিয়ানদের জন্য লার্জ ডিসপ্লে এসি/ডিসি ভোল্টেজ, কারেন্ট ও ক্যাপাসিটর টেস্টার।',
    description: 'ইলেকট্রনিক্স সার্ভিসিং কাজে সবচেয়ে নির্ভরযোগ্য ও জনপ্রিয় ডিজিটাল মাল্টিমিটার DT-9205A। এটি দিয়ে এসি/ডিসি ভোল্টেজ, কারেন্ট, রেজিস্ট্যান্স, ক্যাপাসিট্যান্স, ডায়োড এবং কন্টিনিউটি বাজার টেস্ট করা যায়। বড় ডিসপ্লে এবং রাবার শকপ্রুফ কভার যুক্ত।',
    price: 650,
    discount_price: 550,
    stock: 50,
    min_stock_warning: 8,
    category: 'tools',
    brand: 'DT Tools',
    main_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: '৬ মাসের সার্ভিসিং ওয়ারেন্টি',
    shipping_info: 'সারাদেশে হোম ডেলিভারি ক্যাশ অন ডেলিভারিতে।',
    return_info: '৭ দিনের রিপ্লেসমেন্ট গ্যারান্টি।',
    tags: ['multimeter', 'dt9205a', 'measuring tools', 'electronics tools'],
    features: [
      'লার্জ এলসিডি ডিসপ্লে ভিউয়িং অ্যাঙ্গেল সহ',
      'কন্টিনিউটি বাজার ও ট্রানজিস্টর hFE টেস্টিং',
      'ক্যাপাসিট্যান্স এবং রেজিস্ট্যান্স নিখুঁত পরিমাপ',
      'প্রোটেক্টিভ রাবার হলস্টার কাভার যুক্ত',
    ],
    specifications: [
      { spec_group: 'Measurement', key: 'ডিসি ভোল্টেজ', value: '200mV - 1000V' },
      { spec_group: 'Measurement', key: 'এসি ভোল্টেজ', value: '200mV - 750V' },
      { spec_group: 'Measurement', key: 'ক্যাপাসিট্যান্স', value: '20nF - 200uF' },
      { spec_group: 'Power', key: 'ব্যাটারি', value: '9V ব্যাটারি সহ' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.8,
    review_count: 63,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    title: '৬০W অ্যাডজাস্টেবল টেম্পারেচার সোল্ডারিং আয়রন কিট (60W Soldering Iron with 5 Tips)',
    slug: '60w-adjustable-temperature-soldering-iron-kit',
    sku: 'SW-IRON-60W',
    short_description: '২০০°C থেকে ৪৫০°C টেম্পারেচার কন্ট্রোল তাতাল, ৫ পিস এক্সট্রা বিট ও স্ট্যান্ড সহ।',
    description: 'সার্কিট বোর্ড ও নিখুঁত ইলেকট্রনিক্স সোল্ডারিং কাজের জন্য অ্যাডজাস্টেবল ৬০ ওয়াট সিরামিক কোর সোল্ডারিং আয়রন। সহজেই টেম্পারেচার নব ঘুরিয়ে তাপমাত্রা নিয়ন্ত্রণ করা যায়। সাথে থাকছে বিভিন্ন সাইজের ৫টি অতিরিক্ত আয়রন টিপ ও মিনি স্ট্যান্ড।',
    price: 550,
    discount_price: 450,
    stock: 45,
    min_stock_warning: 6,
    category: 'tools',
    brand: 'DT Tools',
    main_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: '৩ মাসের হিটার কয়েল রিপ্লেসমেন্ট সাপোর্ট',
    shipping_info: '২৪-৪৮ ঘণ্টায় ক্যাশ অন ডেলিভারি।',
    return_info: 'সরাসরি টেস্ট করে নেয়ার সুবিধা।',
    tags: ['soldering iron', 'tatal', 'adjustable iron', 'electronics tools', 'soldering kit'],
    features: [
      '২০০°C - ৪৫০°C নিখুঁত তাপমাত্রা নিয়ন্ত্রণ নব',
      'দ্রুত গরম হওয়ার হাই-গ্রেড সিরামিক হিটার',
      '৫টি ভিন্ন ধরনের রিপ্লেসমেন্ট সোল্ডারিং বিট',
      'হিট-রেজিস্ট্যান্ট সিলিকন গ্রিপ হ্যান্ডেল',
    ],
    specifications: [
      { spec_group: 'Power', key: 'পাওয়ার ওয়াট', value: '60W' },
      { spec_group: 'Thermal', key: 'তাপমাত্রা রেঞ্জ', value: '200°C - 450°C' },
      { spec_group: 'Tips', key: 'টিপস সংখ্যা', value: '৫ পিস কপার প্লেটেড টিপ' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.7,
    review_count: 34,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-010',
    title: 'হেভি ডিউটি অ্যালুমিনিয়াম ডিসোল্ডারিং সাকশন পাম্প (Desoldering Solder Sucker)',
    slug: 'heavy-duty-aluminum-desoldering-pump',
    sku: 'SW-PUMP-DESOLD',
    short_description: 'সার্কিট বোর্ড থেকে রাং তুলতে হাই-সাকশন অ্যালুমিনিয়াম বডি ডিসোল্ডারিং পাম্প।',
    description: 'টিভি, অ্যামপ্লিফায়ার ও সার্কিট বোর্ড সার্ভিসিংয়ের সময় পার্টস খোলার জন্য অত্যন্ত শক্তিশালী সাকশন পাম্প। মেটাল বডি হওয়ায় দীর্ঘস্থায়ী এবং বারবার ব্যবহারে কোনো সমস্যা হয় না। হাই-গ্রেড স্প্রিং এর কারণে এক চাপেই নিখুঁতভাবে রাং পরিষ্কার হয়।',
    price: 220,
    discount_price: 180,
    stock: 60,
    min_stock_warning: 10,
    category: 'tools',
    brand: 'DT Tools',
    main_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: 'চেক অ্যান্ড রিসিভ',
    shipping_info: 'সারাদেশে কুরিয়ার সার্ভিস।',
    return_info: 'ডেলিভারির সময় চেক করুন।',
    tags: ['desoldering pump', 'solder sucker', 'servicing tools'],
    features: [
      'স্ট্রং অ্যালুমিনিয়াম অ্যালয় বডি',
      'উচ্চ ভ্যাকুয়াম সাকশন ক্ষমতা',
      'সহজে পরিষ্কারযোগ্য নজল ফিল্টার',
    ],
    specifications: [
      { spec_group: 'Material', key: 'বডি মেটেরিয়াল', value: 'Aluminum Alloy' },
      { spec_group: 'Type', key: 'অপারেশন', value: 'Manual High-Tension Spring' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: false,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.7,
    review_count: 22,
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-011',
    title: 'অরিজিনাল আসাহি রাং তার (Asahi Solder Wire 100g) ও সার্ভিসিং রজন',
    slug: 'original-asahi-solder-wire-100g-rosin-combo',
    sku: 'SW-SOLDER-ASAHI100',
    short_description: '১০০ গ্রাম অরিজিনাল জাপানি ফর্মুলা আসাহি রাং তার (০.৮ মিমি) এবং প্রিমিয়াম ফ্লাক্স রজন।',
    description: 'মসৃণ ও চকচকে সোল্ডারিং এর জন্য বিশ্বসেরা আসাহি (Asahi) ৬০/৪০ রজন-কোর সোল্ডার ওয়্যার এবং কোয়ালিটি সোল্ডারিং পেস্ট/রজন কম্বো। সহজে গলে এবং জয়েন্ট দীর্ঘ বছর শক্তিশালী থাকে।',
    price: 380,
    discount_price: 320,
    stock: 90,
    min_stock_warning: 12,
    category: 'tools',
    brand: 'DT Tools',
    main_image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: '১০০% অরিজিনাল গ্যারান্টি',
    shipping_info: 'সারা দেশে দ্রুত হোম ডেলিভারি।',
    return_info: 'অরিজিনাল না হলে সম্পূর্ণ টাকা ফেরত।',
    tags: ['solder wire', 'asahi rang', 'rosin flux', 'soldering supplies'],
    features: [
      '৬০/৪০ হাই-গ্রেড টিন/লেড অনুপাত',
      '০.৮ মিমি থিকনেস নিখুঁত কাজের জন্য',
      'ফ্লাক্স কোর সহজে জয়েন্ট ধরায়',
    ],
    specifications: [
      { spec_group: 'Weight', key: 'নিট ওজন', value: '১০০ গ্রাম' },
      { spec_group: 'Diameter', key: 'তারের ব্যাস', value: '0.8 mm' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.9,
    review_count: 58,
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    title: 'ব্লেন্ডার হেভি ডিউটি ১০০% কপার মোটর (৭৫০ ওয়াট ইউনিভার্সাল রিপ্লেসমেন্ট)',
    slug: 'blender-heavy-duty-copper-motor-750w',
    sku: 'SW-BLD-MOTOR-750W',
    short_description: 'যেকোনো ব্লেন্ডারের জন্য ১০০% খাঁটি তামার তারের ৭৫০ ওয়াট হেভি ডিউটি মোটর।',
    description: 'মিয়াকো, নোভা, প্রেস্টিজ সহ সব ধরনের ভারতীয় ও চায়না ব্লেন্ডারের জন্য পারফেক্ট ৭৫০ ওয়াট কপার মোটর। সার্ভিসিং ওয়ার্ল্ড টেস্টে প্রমাণিত হেভি লোড নিতে সক্ষম, দীর্ঘ ব্যবহারে অতিরিক্ত গরম হয় না। সাথে কুলিং ফ্যান এবং থার্মাল কাট-অফ সুইচ রয়েছে।',
    price: 1250,
    discount_price: 1100,
    stock: 26,
    min_stock_warning: 4,
    category: 'blender-parts',
    brand: 'Heavy Copper',
    main_image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: '১ বছরের মোটর কয়েল রিপ্লেসমেন্ট ওয়ারেন্টি',
    shipping_info: '২৪-৪৮ ঘণ্টার মধ্যে সারা দেশে ক্যাশ অন ডেলিভারি।',
    return_info: 'ফিটিং না হলে ৭ দিনের মধ্যে পরিবর্তন সুবিধা।',
    tags: ['blender motor', 'copper motor', '750w motor', 'blender parts', 'servicing world'],
    features: [
      '১০০% পিওর কপার ওয়াইন্ডিং কয়েল',
      '৭৫০ ওয়াট হাই স্পিড টার্বো আরপিএম',
      'থার্মাল ওভারলোড প্রোটেকশন সুইচ যুক্ত',
      'ইউনিভার্সাল মাউন্টিং স্ক্রু পয়েন্ট',
    ],
    specifications: [
      { spec_group: 'Power', key: 'পাওয়ার', value: '750 Watts' },
      { spec_group: 'Winding', key: 'কয়েল উপাদান', value: '100% Pure Copper' },
      { spec_group: 'RPM', key: 'গতিবেগ', value: '18000 - 20000 RPM' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.8,
    review_count: 41,
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    title: 'ব্লেন্ডার জার ইউনিভার্সাল রাবার কাপলার ও ৪-ব্লেড অ্যাসেম্বলি কম্বো (৪ পিস সেট)',
    slug: 'blender-jar-universal-coupler-blade-combo-set',
    sku: 'SW-BLD-COUPLER-SET',
    short_description: 'টেকসই ফুড-গ্রেড স্টিল ব্লেড ও হেভি রাবার কাপলার ৪ পিস সার্ভিসিং কম্বো প্যাক।',
    description: 'ব্লেন্ডার জারের পানি লিক হওয়া ও কাপলার কেটে যাওয়ার তাৎক্ষণিক সমাধান। এতে থাকছে ২ পিস হেভি ডিউটি ইউনিভার্সাল রাবার কাপলার, ১ পিস স্টেইনলেস স্টিল ড্রাই গ্রাইন্ডিং ব্লেড এবং ১ পিস ওয়েট ব্লেন্ডিং ব্লেড কম্বো। যেকোনো স্ট্যান্ডার্ড ব্লেন্ডারে সহজে ফিট হয়।',
    price: 350,
    discount_price: 280,
    stock: 75,
    min_stock_warning: 10,
    category: 'blender-parts',
    brand: 'Heavy Copper',
    main_image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: 'চেক অ্যান্ড রিসিভ',
    shipping_info: 'সারাদেশে দ্রুত ক্যাশ অন ডেলিভারি।',
    return_info: 'সাইজ মিল না থাকলে বদলে নেওয়ার সুযোগ।',
    tags: ['blender coupler', 'blender blade', 'blender repair parts'],
    features: [
      'প্রিমিয়াম অ্যান্টি-স্লিপ থ্রেডেড রাবার কাপলার',
      'জং-প্রতিরোধী স্টেইনলেস স্টিল শার্প ব্লেড',
      'লিকুইড লিকেজ রেজিস্ট্যান্ট সিলিং ওয়াশার সহ',
    ],
    specifications: [
      { spec_group: 'Content', key: 'সেট বিবরণ', value: '২ পিস কাপলার + ২ পিস স্টিল ব্লেড' },
      { spec_group: 'Material', key: 'উপাদান', value: 'Food-Grade Stainless Steel & Rubber' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: false,
    is_new_arrival: true,
    is_on_sale: true,
    average_rating: 4.7,
    review_count: 27,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    title: '২.১ চ্যানেল ব্লুটুথ ৫.০ সাবউফার অডিও অ্যামপ্লিফায়ার বোর্ড (TPA3116D2 50W+50W+100W)',
    slug: '2-1-channel-bluetooth-subwoofer-amplifier-board-tpa3116d2',
    sku: 'SW-AMP-TPA3116',
    short_description: '২০০ ওয়াট পিক আউটপুট ২.১ চ্যানেল ব্লুটুথ হাই-ফিডেলিটি বেস সাবউফার অ্যামপ্লিফায়ার।',
    description: 'হোম সাউন্ড সিস্টেম ও ডিআইওয়াই স্পিকার বক্স তৈরির জন্য দুর্দান্ত TPA3116D2 ২.১ চ্যানেল ব্লুটুথ অ্যামপ্লিফায়ার বোর্ড। ৫০ ওয়াট লেফট + ৫০ ওয়াট রাইট এবং ১০০ ওয়াট ডেডিকেটেড সাবউফার আউটপুট। এতে বেস ও ট্রিবল আলাদা অ্যাডজাস্টমেন্ট নব রয়েছে। ১২V থেকে ২৪V ডিসি পাওয়ারে চমৎকার কাজ করে।',
    price: 1350,
    discount_price: 1200,
    stock: 30,
    min_stock_warning: 5,
    category: 'audio-amp',
    brand: 'Servicing World',
    main_image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
    video_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
    youtube_video_id: 'UCo60TsGBAlADhFamHpr4sJQ',
    warranty_info: '৩ মাসের রিপ্লেসমেন্ট সাপোর্ট (শর্ট বাদে)',
    shipping_info: 'সারা দেশে দ্রুত ক্যাশ অন ডেলিভারি।',
    return_info: '৭ দিনের কার্যকারিতা গ্যারান্টি।',
    tags: ['amplifier board', 'bluetooth amp', 'subwoofer board', 'audio parts', 'tpa3116d2'],
    features: [
      '৫০W + ৫০W স্টেরিও + ১০০W হেভি সাবউফার মোট ২০০W',
      'লেটেস্ট ব্লুটুথ ৫.০ ওয়ারলেস অডিও ও AUX ইনপুট',
      'পৃথক সাবউফার ফ্রিকোয়েন্সি ও ভলিউম কন্ট্রোল নব',
      'অ্যালুমিনিয়াম হিটসিঙ্ক সমৃদ্ধ দীর্ঘস্থায়ী ডিজাইন',
    ],
    specifications: [
      { spec_group: 'Power', key: 'অপারেটিং ভোল্টেজ', value: 'DC 12V - 24V (5A+ Recommended)' },
      { spec_group: 'Audio', key: 'চ্যানেল', value: '2.1 Channel (Left, Right, Bass)' },
      { spec_group: 'Chip', key: 'অ্যামপ্লিফায়ার আইসি', value: 'Dual TPA3116D2 Class D' },
    ],
    is_published: true,
    is_featured: true,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.9,
    review_count: 36,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-015',
    title: '১২V ব্লুটুথ ইউএসবি এফএম অডিও ডিকোডার মডিউল রিমোট সহ (MP3 Player Board)',
    slug: '12v-bluetooth-usb-fm-audio-decoder-module-with-remote',
    sku: 'SW-MP3-MOD-12V',
    short_description: 'যেকোনো সাউন্ড বক্সে ব্লুটুথ, ইউএসবি পেনড্রাইভ, মেমোরি কার্ড ও এফএম রেডিও যোগ করার কিট।',
    description: 'পুরাতন অ্যামপ্লিফায়ার বা সাউন্ড বক্সকে স্মার্ট করতে জনপ্রিয় ১২ ভোল্ট ব্লুটুথ এমপিথ্রি ডিকোডার প্যানেল। এতে ব্লুটুথ ৫.০, ইউএসবি পোর্ট, টিএফ কার্ড স্লট, এফএম রেডিও ও রিমোট কন্ট্রোল সুবিধা রয়েছে। যেকোনো ১২ ভোল্ট লাইন দিয়ে সহজে চালানো যায়।',
    price: 250,
    discount_price: 190,
    stock: 80,
    min_stock_warning: 10,
    category: 'audio-amp',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: 'চেক অ্যান্ড টেস্টেড গ্যারান্টি',
    shipping_info: 'সারাদেশে ক্যাশ অন ডেলিভারি।',
    return_info: 'ডেলিভারির সময় চেক করে নিন।',
    tags: ['mp3 module', 'bluetooth module', 'audio card', 'fm module'],
    features: [
      'ওয়্যারলেস ব্লুটুথ ৫.০ অডিও স্ট্রিমিং',
      'ইউএসবি ও মেমোরি কার্ড থেকে সরাসরি গান প্লেব্যাক',
      'ইনবিল্ট ডিজিটাল এফএম রেডিও',
      'রিমোট কন্ট্রোল ও কানেক্টিং ক্যাবল সাথে ফ্রি',
    ],
    specifications: [
      { spec_group: 'Power', key: 'ভোল্টেজ', value: 'DC 7V - 12V' },
      { spec_group: 'Format', key: 'অডিও ফরম্যাট', value: 'MP3 / WMA / WAV / FLAC' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: true,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.7,
    review_count: 48,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-016',
    title: '১২ ভোল্ট ৫ অ্যাম্পিয়ার এসএমপিএস পাওয়ার অ্যাডাপ্টার (12V 5A Power Adapter)',
    slug: '12v-5a-smps-power-adapter-dc-jack',
    sku: 'SW-PWR-12V5A',
    short_description: 'সিসি ক্যামেরা, এলইডি লাইট স্ট্রিপ ও অ্যামপ্লিফায়ারের জন্য পিওর ১২V ৫A পাওয়ার অ্যাডাপ্টার।',
    description: 'স্থায়ী ও নিয়ন্ত্রিত ১২ ভোল্ট ৫ অ্যাম্পিয়ার এসএমপিএস পাওয়ার অ্যাডাপ্টার। ওভার-ভোল্টেজ, শর্ট-সার্কিট ও ওভার-লোড প্রোটেকশন সার্কিট যুক্ত। এটি দিয়ে সিসি ক্যামেরা সেট, অডিও অ্যামপ্লিফায়ার ও ডিসি এলইডি স্ট্রিপ নিরাপদে পরিচালনা করা যায়।',
    price: 550,
    discount_price: 480,
    stock: 55,
    min_stock_warning: 8,
    category: 'power-battery',
    brand: 'Servicing World',
    main_image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: '৬ মাসের রিপ্লেসমেন্ট ওয়ারেন্টি',
    shipping_info: '২৪-৪৮ ঘণ্টার মধ্যে সারা দেশে হোম ডেলিভারি।',
    return_info: '৭ দিনের রিপ্লেসমেন্ট সুবিধা।',
    tags: ['power adapter', '12v 5a', 'power supply', 'smps', 'cc camera adapter'],
    features: [
      '১০০% পিওর ১২V ৫A রেটেড আউটপুট ক্ষমতা',
      'লো রিপল ও নয়েজ মুক্ত ফিল্টার সার্কিট',
      'স্ট্যান্ডার্ড ৫.৫ x ২.১ মিমি ডিসি জ্যাক পিন',
    ],
    specifications: [
      { spec_group: 'Input', key: 'ইনপুট', value: 'AC 100-240V 50/60Hz' },
      { spec_group: 'Output', key: 'আউটপুট', value: 'DC 12V 5A (60 Watts Max)' },
      { spec_group: 'Connector', key: 'প্লাগ টাইপ', value: '5.5mm x 2.1mm / 2.5mm' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: false,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.8,
    review_count: 31,
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-017',
    title: '৩এস ১২.৬V ৪০A লিথিয়াম আয়ন ব্যাটারি বিএমএস প্রোটেকশন বোর্ড (3S 40A BMS Board)',
    slug: '3s-40a-bms-lithium-battery-protection-board',
    sku: 'SW-BMS-3S40A',
    short_description: '১৮৬৫০ ব্যাটারি প্যাক ও ড্রিল মেশিনের জন্য ৩এস ৪০ অ্যাম্পিয়ার ব্যালেন্সড বিএমএস মডিউল।',
    description: '৩ পিস ১৮৬৫০ লিথিয়াম ব্যাটারি দিয়ে ১২ ভোল্ট ব্যাটারি প্যাক তৈরির সেরা বিএমএস সুরক্ষা বোর্ড। এটি ব্যাটারির ওভার-চার্জিং, ওভার-ডিসচার্জিং ও শর্ট-সার্কিট প্রতিরোধ করে এবং প্রতিটি সেলের ভোল্টেজ ব্যালেন্স বজায় রাখে। কর্ডলেস ড্রিল মেশিন ও ইউপিএস তৈরিতে আদর্শ।',
    price: 280,
    discount_price: 220,
    stock: 65,
    min_stock_warning: 10,
    category: 'power-battery',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: 'চেক অ্যান্ড টেস্টেড',
    shipping_info: 'সারাদেশে ক্যাশ অন ডেলিভারি।',
    return_info: 'কুরিয়ার থেকে ডেলিভারি নিয়ে চেক করার সুযোগ।',
    tags: ['bms board', '3s 40a', 'lithium battery', '18650 bms', 'battery protection'],
    features: [
      'সেল ব্যালেন্সিং চার্জিং টেকনোলজি',
      '৪০ অ্যাম্পিয়ার সর্বোচ্চ পিক ডিসচার্জ সাপোর্ট',
      'ওভারলোড ও শর্ট সার্কিট অটো কাট-অফ',
    ],
    specifications: [
      { spec_group: 'Battery', key: 'ব্যাটারি সিরিজ', value: '3S (3x 3.7V / 4.2V Cells)' },
      { spec_group: 'Voltage', key: 'চার্জিং ভোল্টেজ', value: 'DC 12.6V - 13.6V' },
      { spec_group: 'Current', key: 'কন্টিনিউয়াস কারেন্ট', value: '40A Max' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: false,
    is_new_arrival: true,
    is_on_sale: true,
    average_rating: 4.8,
    review_count: 23,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-018',
    title: '২ মেগাপিক্সেল নাইট ভিশন এইচডি ডোম সিসি ক্যামেরা ও বিএনসি কানেক্টর কিট',
    slug: '2mp-night-vision-hd-dome-cc-camera-kit',
    sku: 'SW-CAM-DOME-2MP',
    short_description: '১০৮০পি ক্রিস্টাল ক্লিয়ার নাইট ভিশন ইনডোর ডোম সিসি ক্যামেরা ও বিএনসি পিন সেট।',
    description: 'দোকান, বাসা ও গুদামের সার্বক্ষণিক নজরদারির জন্য ২ মেগাপিক্সেল ফুল এইচডি নাইট ভিশন ডোম সিসি ক্যামেরা। কুয়াশা বা রাতের ঘুটঘুটে অন্ধকারেও ইনফ্রারেড নাইট ভিশনে নিখুঁত ছবি ক্যাপচার করে। সাথে থাকছে ২ পিস কপার বিএনসি পিন ও ডিসি পাওয়ার জ্যাক।',
    price: 1250,
    discount_price: 1050,
    stock: 20,
    min_stock_warning: 3,
    category: 'cc-camera',
    brand: 'China Universal',
    main_image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    ],
    warranty_info: '১ বছরের সার্ভিসিং ওয়ারেন্টি',
    shipping_info: 'সারা দেশে দ্রুত ক্যাশ অন ডেলিভারি।',
    return_info: '৭ দিনের রিপ্লেসমেন্ট সুবিধা।',
    tags: ['cc camera', 'dome camera', 'night vision camera', 'cctv kit', 'security'],
    features: [
      '২ মেগাপিক্সেল ১০৮০পি ফুল এইচডি রেজোলিউশন',
      'স্মার্ট আইআর নাইট ভিশন ২০ মিটার রেঞ্জ',
      'ওয়াইড অ্যাঙ্গেল ৩.৬ মিমি এইচডি লেন্স',
      'ইনস্টলেশন এক্সেসরিজ ও কানেক্টর সহ সম্পূর্ণ কিট',
    ],
    specifications: [
      { spec_group: 'Camera', key: 'রেজোলিউশন', value: '2.0 MP (1920x1080 Full HD)' },
      { spec_group: 'Vision', key: 'নাইট ভিশন', value: 'স্মার্ট আইআর ফিল্টার (২০ মিটার)' },
      { spec_group: 'Power', key: 'পাওয়ার ইনপুট', value: 'DC 12V 1A' },
    ],
    is_published: true,
    is_featured: false,
    is_bestseller: false,
    is_new_arrival: false,
    is_on_sale: true,
    average_rating: 4.7,
    review_count: 18,
    created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'ban-1',
    title: '৩২ খেলা ও ১৬ খেলার ডিজিটাল লকার মেশিন',
    subtitle: 'বিয়ে বাড়ি, পূজা ও সব ধরনের ডেকোরেশন লাইটের জন্য বিশ্বস্ত মরিচ বাতি খেলানোর ডিজিটাল লকার মেশিন ও কন্ট্রোলার। সরাসরি সার্ভিসিং ওয়ার্ল্ড টেস্টেড।',
    badge: 'ইউটিউব ল্যাব টেস্টেড',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    cta_text: 'লকার মেশিন দেখুন',
    cta_url: '/shop?category=chaser-machine',
    display_order: 1,
    is_active: true,
  },
  {
    id: 'ban-2',
    title: 'ইউনিভার্সাল এলইডি টিভি মাদারবোর্ড ও ব্যাকলাইট টেস্টার',
    subtitle: 'যেকোনো এলইডি টিভির জন্য T.V56/53 মাদারবোর্ড কিট এবং ০-৩০০V ব্যাকলাইট টেস্টার। টেকনিশিয়ান ও মেকানিকদের জন্য আসল পার্টস।',
    badge: 'সেরা টেকনিশিয়ান চয়েস',
    image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=1200&q=80',
    cta_text: 'টিভি পার্টস কিনুন',
    cta_url: '/shop?category=tv-parts',
    display_order: 2,
    is_active: true,
  },
];

export const INITIAL_SETTINGS: SiteSettings = {
  store_name: 'SERVICING WORLD',
  tagline: 'ডিজিটাল লকার মেশিন, মরিচ বাতি, টিভি রিপেয়ারিং পার্টস ও ইলেকট্রনিক্স সার্ভিসিং টুলস',
  phone: '+880 1785-958427',
  email: 'support@servicingworld.com',
  address: 'হারতা বাজার, গার্লস স্কুল রোড, উজিরপুর, বরিশাল, বাংলাদেশ',
  youtube_channel_url: 'https://www.youtube.com/channel/UCo60TsGBAlADhFamHpr4sJQ',
  youtube_channel_name: 'Servicing World',
  currency: 'BDT',
  currency_symbol: '৳',
  free_shipping_threshold: 2000.0,
  tax_rate: 0.0,
  is_maintenance_mode: false,
  announcement_badge: 'সার্ভিসিং ওয়ার্ল্ড',
  announcement_text: '⚡ সারাদেশে দ্রুত ক্যাশ অন ডেলিভারি (৳২,০০০ এর অর্ডারে ফ্রি ডেলিভারি)! সরাসরি যোগাযোগ: 01785-958427',
  is_announcement_active: true,
};

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'c-1',
    code: 'WELCOME10',
    description: 'নতুন গ্রাহকদের জন্য ১০% মূল্যছাড়',
    discount_type: 'percentage',
    discount_value: 10,
    min_order_amount: 1000,
    is_active: true,
  },
  {
    id: 'c-2',
    code: 'SW200',
    description: '৳২,৫০০ এর বেশি অর্ডারে ৳২০০ ফ্ল্যাট ছাড়',
    discount_type: 'fixed',
    discount_value: 200,
    min_order_amount: 2500,
    is_active: true,
  },
  {
    id: 'c-3',
    code: 'YOUTUBE15',
    description: 'ইউটিউব সাবস্ক্রাইবার স্পেশাল ১৫% ডিসকাউন্ট',
    discount_type: 'percentage',
    discount_value: 15,
    min_order_amount: 1500,
    is_active: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-001',
    customer_name: 'সোহাগ মিয়া, ডেকোরেটর ও ইলেকট্রিশিয়ান',
    rating: 5,
    title: '৩২ খেলার লকার মেশিনটা অসাধারণ!',
    comment: 'ইউটিউবে বিশ্বরজিৎ দাদার ভিডিও দেখে অর্ডার করেছিলাম। বরিশালের হারতা বাজার থেকে খুব দ্রুত পাঠিয়েছেন। ৩২ টা চ্যানেলের খেলাই একদম স্মুথ কাজ করছে। বিয়ের গেট ডেকোরেশনে দারুণ আলো ছড়াচ্ছে।',
    is_verified_purchase: true,
    is_approved: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'rev-2',
    product_id: 'prod-005',
    customer_name: 'কামরুল হাসান, টিভি টেকনিশিয়ান',
    rating: 5,
    title: 'এলইডি টিভি মাদারবোর্ড কিট পারফেক্ট',
    comment: '৩২ ইঞ্চি ওয়ালটন টিভির প্যানেলে ফিট করেছি। রেজোলিউশন সফটওয়্যার ইউএসবি দিয়ে সাথে সাথে নিয়ে নিয়েছে। ছবি এবং সাউন্ড খুবই স্পষ্ট। দামেও সাশ্রয়ী।',
    is_verified_purchase: true,
    is_approved: true,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'rev-3',
    product_id: 'prod-008',
    customer_name: 'আমিনুল ইসলাম, ইলেকট্রনিক্স রিপেয়ারার',
    rating: 5,
    title: 'ডিটি-৯২০৫এ মাল্টিমিটার খুব একুরেট',
    comment: 'ক্যাপাসিটর ও রেজিস্ট্যান্স খুব দ্রুত পরিমাপ করে। ডিসপ্লে অনেক বড় হওয়ায় স্পষ্ট দেখা যায়। রাবার কভার থাকায় হাত থেকে পড়লেও সমস্যা হয় না।',
    is_verified_purchase: true,
    is_approved: true,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
];

export const INITIAL_CUSTOMERS: any[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@servicingworld.com',
    full_name: 'বিশ্বরজিৎ দত্ত (Bishowjit Datta)',
    role: 'super_admin',
    phone: '+880 1785-958427',
    orders_count: 24,
    total_spent: 68500,
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
  {
    id: 'usr-cust-02',
    email: 'tanvir.ahmed@techmaker.bd',
    full_name: 'তানভীর আহমেদ',
    role: 'customer',
    phone: '+880 1812-345678',
    orders_count: 5,
    total_spent: 18450,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'usr-cust-03',
    email: 'rakibul.hasan@iotlab.com',
    full_name: 'রাকিবুল হাসান',
    role: 'customer',
    phone: '+880 1919-876543',
    orders_count: 3,
    total_spent: 9800,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

export const INITIAL_FAQS = [
  {
    id: 'faq-1',
    question: 'সার্ভিসিং ওয়ার্ল্ডের প্রোডাক্টগুলো কি আসল এবং টেস্টেড?',
    answer: 'হ্যাঁ, আমাদের ইউটিউব চ্যানেলে দেখানো প্রতিটি প্রোডাক্ট (ডিজিটাল লকার মেশিন, টিভি মাদারবোর্ড, মাল্টিমিটার, ব্লেন্ডার মোটর ইত্যাদি) হার্ডওয়্যার ল্যাবে মেপে এবং টেস্ট করে স্টক করা হয়। ত্রুটিপূর্ণ কোনো পণ্য বিক্রি করা হয় না।',
    category: 'পণ্য ও টেস্টিং',
    display_order: 1,
    is_published: true,
  },
  {
    id: 'faq-2',
    question: 'সারা দেশে ডেলিভারি কীভাবে পাওয়া যায় এবং কত দিন সময় লাগে?',
    answer: 'আমরা সুন্দরবন কুরিয়ার, এসএ পরিবহন, স্টিডফাস্ট ও রেডএক্সের মাধ্যমে সারা বাংলাদেশে ক্যাশ অন ডেলিভারিতে হোম ডেলিভারি দেই। সাধারণত ২৪ থেকে ৪৮ ঘণ্টার মধ্যে ডেলিভারি সম্পন্ন হয়।',
    category: 'ডেলিভারি ও শিপিং',
    display_order: 2,
    is_published: true,
  },
  {
    id: 'faq-3',
    question: 'পণ্য নষ্ট পেলে বা কাজ না করলে কি বদলানো যাবে?',
    answer: 'অবশ্যই। ডেলিভারি পাওয়ার পর প্রোডাক্টে কোনো সমস্যা থাকলে ৭ দিনের মধ্যে সরাসরি বদলিয়ে নতুন প্রোডাক্ট নেওয়ার সুবিধা রয়েছে। আমাদের হটলাইন নম্বরে (01785-958427) যোগাযোগ করলেই সমাধান পাবেন।',
    category: 'ওয়ারেন্টি ও রিটার্ন',
    display_order: 3,
    is_published: true,
  },
  {
    id: 'faq-4',
    question: 'আপনাদের দোকান বা শোরুম কোথায় অবস্থিত?',
    answer: 'আমাদের প্রধান শপ ও সার্ভিস সেন্টার: হারতা বাজার, গার্লস স্কুল রোড, উজিরপুর, বরিশাল। সরাসরি এসেও পণ্য যাচাই করে কেনা যায়।',
    category: 'ঠিকানা ও যোগাযোগ',
    display_order: 4,
    is_published: true,
  },
];

export const INITIAL_CMS_PAGES = [
  {
    id: 'cms-privacy',
    slug: 'privacy',
    title: 'প্রাইভেসি পলিসি ও তথ্য নিরাপত্তা',
    content: 'সার্ভিসিং ওয়ার্ল্ড গ্রাহকদের তথ্যের পূর্ণ গোপনীয়তা বজায় রাখে। আপনার ফোন নম্বর এবং ঠিকানা কেবল পণ্য ডেলিভারি ও যোগাযোগের কাজে ব্যবহার করা হয়।',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cms-terms',
    slug: 'terms',
    title: 'শর্তাবলী ও নিয়মাবলী',
    content: 'সার্ভিসিং ওয়ার্ল্ড থেকে অর্ডার করার সময় সঠিক যোগাযোগের তথ্য প্রদান করতে হবে। ইলেকট্রনিক যন্ত্রাংশ ব্যবহারের নিয়ম মেনে সংযোগ দিন।',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cms-shipping',
    slug: 'shipping-policy',
    title: 'শিপিং ও ডেলিভারি পলিসি',
    content: 'প্রতিটি পার্সেল বাবল র‍্যাপ এবং শকপ্রুফ সুরক্ষিত প্যাকেজিংয়ে পাঠানো হয়। ৳২,০০০ টাকার উপরে যেকোনো অর্ডারে সারা বাংলাদেশে সম্পূর্ণ ফ্রি ডেলিভারি।',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cms-returns',
    slug: 'return-policy',
    title: 'ওয়ারেন্টি ও রিটার্ন পলিসি',
    content: 'লকার মেশিন এবং ইলেকট্রনিক পণ্যে নির্ধারিত সার্ভিসিং ওয়ারেন্টি দেওয়া হয়। ত্রুটিপূর্ণ পণ্য পেলে দ্রুত পরিবর্তন সুবিধা বিদ্যমান।',
    updated_at: new Date().toISOString(),
  },
];
